# 작업형2
- 빅데이터 분석기사 3회 실기
- 제공된 데이터
    - train.csv
    - test.csv
- 예측할 컬럼 : TravelInsurance

### 시험에서 제공된 코드
~~~
import pandas as pd
a = pd.read_csv("train.csv")
b = pd.read_csv('test.csv')

pd.DataFrame(변수).to_csv('000000000.csv')
~~~


### 보험가입 확률을 묻는 문제
~~~
# csv 형태
# index,y_pred
# 0,0.152467
# 1,0.961511
# 2,0.151313
# 3,0.236632
...
# 494,0.121372
# 495,0.965155
# 496,0.986405

~~~

## 데이터 불러오기

In [71]:
import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

## EDA

In [72]:
# 크기 확인
print(train.shape, test.shape)
#test의 컬럼이 하나 적다는 걸 알 수 있음.
print(train.head())
print('--------------------------')
print(test.head())
# 따라서 target 값은 train의 travelinsurance

(1490, 10) (497, 9)
   Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0         888   28  Private Sector/Self Employed           Yes       1250000
1        1308   31  Private Sector/Self Employed           Yes       1250000
2         151   29  Private Sector/Self Employed           Yes       1200000
3         396   33             Government Sector           Yes        650000
4         135   28  Private Sector/Self Employed           Yes        800000

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No
1              7                1            No                  No
2              7                0            No                  No
3              6                1            No                  No
4              6                0            No                 Yes

   TravelInsurance
0                0
1                0
2                1
3                1
4                1
--------------------------
   Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0         920   32             Government Sector           Yes        650000
1         777   27             Government Sector           Yes        500000
2         696   32             Government Sector           Yes        350000
3         907   26  Private Sector/Self Employed           Yes       1400000
4         675   27  Private Sector/Self Employed            No        350000

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad
0              5                0            No                  No
1              5                0            No                  No
2              2                0            No                  No
3              6                0            No                 Yes
4              3                0            No                  No

In [73]:
# 타입 확인
print(train.info()) # 오브젝트형 4개, test와 train 동일.
print('----------')
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1490 non-null   int64
 1   Age                  1490 non-null   int64
 2   Employment Type      1490 non-null   object
 3   GraduateOrNot        1490 non-null   object
 4   AnnualIncome         1490 non-null   int64
 5   FamilyMembers        1490 non-null   int64
 6   ChronicDiseases      1490 non-null   int64
 7   FrequentFlyer        1490 non-null   object
 8   EverTravelledAbroad  1490 non-null   object
 9   TravelInsurance      1490 non-null   int64
dtypes: int64(6), object(4)
memory usage: 116.5+ KB
None
----------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           497 non-null    int64
 1   Age                  497 non-null    int64
 2   Employment Type      497 non-null    object
 3   GraduateOrNot        497 non-null    object
 4   AnnualIncome         497 non-null    int64
 5   FamilyMembers        497 non-null    int64
 6   ChronicDiseases      497 non-null    int64
 7   FrequentFlyer        497 non-null    object
 8   EverTravelledAbroad  497 non-null    object
dtypes: int64(5), object(4)
memory usage: 35.1+ KB
None

In [74]:
# 결측치 확인
print(train.isnull().sum())
print(test.isnull().sum())

# train / test 모두 결측치는 없음을 알 수 있음.

Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64
Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
dtype: int64

In [75]:
# 기초 통계 획인
print(train.describe())
print('-------------------')
print(test.describe())
# outliar는 딱히 없는 것으로 추정. 연령대는 20대~ 30대로 분류하기가 애매

        Unnamed: 0          Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
count  1490.000000  1490.000000  1.490000e+03    1490.000000      1490.000000
mean    992.277181    29.600000  9.310738e+05       4.755705         0.280537
std     566.637006     2.887829  3.763057e+05       1.603613         0.449412
min       0.000000    25.000000  3.000000e+05       2.000000         0.000000
25%     502.250000    28.000000  6.000000e+05       4.000000         0.000000
50%     994.500000    29.000000  9.000000e+05       5.000000         0.000000
75%    1479.750000    32.000000  1.250000e+06       6.000000         1.000000
max    1983.000000    35.000000  1.800000e+06       9.000000         1.000000

       TravelInsurance
count      1490.000000
mean          0.352349
std           0.477862
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
-------------------
        Unnamed: 0         Age  AnnualIncome  FamilyMembers  ChronicDiseases
count   497.000000  497.000000  4.970000e+02     497.000000       497.000000
mean    995.167002   29.800805  9.378270e+05       4.744467         0.269618
std     595.113355    2.986286  3.788348e+05       1.629211         0.444208
min       5.000000   25.000000  3.000000e+05       2.000000         0.000000
25%     468.000000   28.000000  6.000000e+05       4.000000         0.000000
50%     986.000000   29.000000  9.000000e+05       5.000000         0.000000
75%    1550.000000   33.000000  1.250000e+06       6.000000         1.000000
max    1986.000000   35.000000  1.750000e+06       9.000000         1.000000

In [76]:
# 기초 통계 획인 object
print(test.describe(include = 'object'))
print(train.describe(include = 'object'))

# object값은 기본적으로 0/1 두가지 경우의 수로 이뤄져 있음

                     Employment Type GraduateOrNot FrequentFlyer  \
count                            497           497           497
unique                             2             2             2
top     Private Sector/Self Employed           Yes            No
freq                             361           422           395

       EverTravelledAbroad
count                  497
unique                   2
top                     No
freq                   398
                     Employment Type GraduateOrNot FrequentFlyer  \
count                           1490          1490          1490
unique                             2             2             2
top     Private Sector/Self Employed           Yes            No
freq                            1056          1270          1175

       EverTravelledAbroad
count                 1490
unique                   2
top                     No
freq                  1209

In [77]:
# 타겟(레이블)
print(train['TravelInsurance'].value_counts())
# 비가입 965 / 가입 525

TravelInsurance
0    965
1    525
Name: count, dtype: int64

## 데이터 전처리 및 피처엔지니어링

In [78]:
# 수치형 데이터와 범주형 데이터 분리
n_train = train.select_dtypes(exclude = 'object').copy()
c_train = train.select_dtypes(include = 'object').copy()
n_test = test.select_dtypes(exclude = 'object').copy()
c_test = test.select_dtypes(include = 'object').copy()

print(n_train.shape, c_train.shape, n_test.shape, n_train.shape)

(1490, 6) (1490, 4) (497, 5) (1490, 6)

In [79]:
# 수치형 변수 스케일링
from sklearn.preprocessing import MinMaxScaler
# 수치형 컬럼을 우선 가져온다
cols = ['Age', 'AnnualIncome', 'FamilyMembers', 'ChronicDiseases']
print(cols)
scaler = MinMaxScaler()

n_train[cols] = scaler.fit_transform(n_train[cols])
n_test[cols] = scaler.transform(n_test[cols])
print(n_train.head())
print(n_test.head())

['Age', 'AnnualIncome', 'FamilyMembers', 'ChronicDiseases']
   Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
0         888  0.3      0.633333       0.571429              1.0
1        1308  0.6      0.633333       0.714286              1.0
2         151  0.4      0.600000       0.714286              0.0
3         396  0.8      0.233333       0.571429              1.0
4         135  0.3      0.333333       0.571429              0.0

   TravelInsurance
0                0
1                0
2                1
3                1
4                1
   Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases
0         920  0.7      0.233333       0.428571              0.0
1         777  0.2      0.133333       0.428571              0.0
2         696  0.7      0.033333       0.000000              0.0
3         907  0.1      0.733333       0.571429              0.0
4         675  0.2      0.033333       0.142857              0.0

In [80]:
# 범주형 변수 인코딩 - 원핫인코딩 사용 (get_dummies)
display(c_train.head())
c_train = pd.get_dummies(c_train)
c_test = pd.get_dummies(c_test)
print(c_train.head())

,Employment Type,GraduateOrNot,FrequentFlyer,EverTravelledAbroad
0,Private Sector/Self Employed,Yes,No,No
1,Private Sector/Self Employed,Yes,No,No
2,Private Sector/Self Employed,Yes,No,No
3,Government Sector,Yes,No,No
4,Private Sector/Self Employed,Yes,No,Yes

   Employment Type_Government Sector  \
0                              False
1                              False
2                              False
3                               True
4                              False

   Employment Type_Private Sector/Self Employed  GraduateOrNot_No  \
0                                          True             False
1                                          True             False
2                                          True             False
3                                         False             False
4                                          True             False

   GraduateOrNot_Yes  FrequentFlyer_No  FrequentFlyer_Yes  \
0               True              True              False
1               True              True              False
2               True              True              False
3               True              True              False
4               True              True              False

   EverTravelledAbroad_No  EverTravelledAbroad_Yes
0                    True                    False
1                    True                    False
2                    True                    False
3                    True                    False
4                   False                     True

In [81]:
# 분리한 데이터 다시 합침
train = pd.concat([n_train, c_train], axis = 1)
test = pd.concat([n_test, c_test], axis = 1)
print(train.head())
print(test.head())

   Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
0         888  0.3      0.633333       0.571429              1.0
1        1308  0.6      0.633333       0.714286              1.0
2         151  0.4      0.600000       0.714286              0.0
3         396  0.8      0.233333       0.571429              1.0
4         135  0.3      0.333333       0.571429              0.0

   TravelInsurance  Employment Type_Government Sector  \
0                0                              False
1                0                              False
2                1                              False
3                1                               True
4                1                              False

   Employment Type_Private Sector/Self Employed  GraduateOrNot_No  \
0                                          True             False
1                                          True             False
2                                          True             False
3                                         False             False
4                                          True             False

   GraduateOrNot_Yes  FrequentFlyer_No  FrequentFlyer_Yes  \
0               True              True              False
1               True              True              False
2               True              True              False
3               True              True              False
4               True              True              False

   EverTravelledAbroad_No  EverTravelledAbroad_Yes
0                    True                    False
1                    True                    False
2                    True                    False
3                    True                    False
4                   False                     True
   Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
0         920  0.7      0.233333       0.428571              0.0
1         777  0.2      0.133333       0.428571              0.0
2         696  0.7      0.033333       0.000000              0.0
3         907  0.1      0.733333       0.571429              0.0
4         675  0.2      0.033333       0.142857              0.0

   Employment Type_Government Sector  \
0                               True
1                               True
2                               True
3                              False
4                              False

   Employment Type_Private Sector/Self Employed  GraduateOrNot_No  \
0                                         False             False
1                                         False             False
2                                         False             False
3                                          True             False
4                                          True              True

   GraduateOrNot_Yes  FrequentFlyer_No  FrequentFlyer_Yes  \
0               True              True              False
1               True              True              False
2               True              True              False
3               True              True              False
4              False              True              False

   EverTravelledAbroad_No  EverTravelledAbroad_Yes
0                    True                    False
1                    True                    False
2                    True                    False
3                   False                     True
4                    True                    False

## 검증데이터 분리

In [82]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train.drop(['TravelInsurance'], axis = 1),
                                            train['TravelInsurance'],
                                            test_size = 0.1,
                                            random_state = 2024) #검증 데이터 + 타겟값
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

# 검증 데이터는 1341 / 테스트 데이터는 149개.

(1341, 13) (149, 13) (1341,) (149,)

## 모델 학습 및 예측

In [83]:
# 랜덤포레스트 (분류문제. 보험 가입인지 아닌지를 묻는 문제이므로)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 400, max_depth = 9, random_state = 2024)
model.fit(X_tr, y_tr)
pred = model.predict_proba(X_val)
print(pred[:,1])

# roc_auc_score를 가져와 평가. 0.7487329434697856
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_val, pred[:,1]))

[0.392323   0.16201408 0.18215496 0.08096729 0.13756955 0.34965246
 0.81600119 0.18207524 0.14625697 0.99034916 0.96004866 0.66344225
 0.27848554 0.9523631  0.22993145 0.12952917 0.955456   0.14790124
 0.987938   0.66630945 0.19770064 0.11979357 0.24217687 0.20021775
 0.15640944 0.62291084 0.20422475 0.17579052 0.2517097  0.13294715
 0.14726017 0.38637992 0.79031851 0.21887748 0.11898691 0.11898691
 0.11933412 0.78044782 0.18462047 0.83881778 0.97648202 0.97134166
 0.4546413  0.16704396 0.18586552 0.1601578  0.13289464 0.84539871
 0.2286907  0.53400605 0.19254445 0.88373354 0.14916467 0.82314359
 0.18910568 0.20711906 0.14157225 0.13910681 0.21571797 0.18400783
 0.11219348 0.2747632  0.2162998  0.15952848 0.86446328 0.16917132
 0.22648489 0.39991593 0.54778146 0.21777965 0.17481472 0.98881709
 0.99697977 0.02428073 0.9805692  0.06654636 0.16452585 0.23527553
 0.17321247 0.23016308 0.2142551  0.13228583 0.12704307 0.26094342
 0.24205081 0.10659002 0.80744103 0.99822589 0.08615142 0.98975319
 0.34668169 0.8065744  0.30024133 0.44941429 0.18988641 0.26670569
 0.45193172 0.2340874  0.37631224 0.19521119 0.81021821 0.29276816
 0.2566616  0.21870332 0.18491312 0.16981389 0.12753285 0.18722667
 0.87878139 0.19573806 0.43157431 0.98633365 0.17796394 0.92720444
 0.1924522  0.01891545 0.2832855  0.37031674 0.19224648 0.15351565
 0.97610522 0.24176676 0.18029123 0.20697383 0.29291528 0.2322349
 0.1136824  0.29073082 0.186491   0.98324781 0.85230533 0.18807779
 0.17179024 0.29009072 0.27704682 0.10534172 0.97050168 0.8853373
 0.16699537 0.18231212 0.08290796 0.28991366 0.26720345 0.41822101
 0.20188626 0.16030955 0.25259745 0.40007171 0.05872088]
0.7684210526315789

## 예측

In [85]:
# test 예측
print(test.head())
print(test.sample())
pred = model.predict_proba(test)[:,1]

   Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
0         920  0.7      0.233333       0.428571              0.0
1         777  0.2      0.133333       0.428571              0.0
2         696  0.7      0.033333       0.000000              0.0
3         907  0.1      0.733333       0.571429              0.0
4         675  0.2      0.033333       0.142857              0.0

   Employment Type_Government Sector  \
0                               True
1                               True
2                               True
3                              False
4                              False

   Employment Type_Private Sector/Self Employed  GraduateOrNot_No  \
0                                         False             False
1                                         False             False
2                                         False             False
3                                          True             False
4                                          True              True

   GraduateOrNot_Yes  FrequentFlyer_No  FrequentFlyer_Yes  \
0               True              True              False
1               True              True              False
2               True              True              False
3               True              True              False
4              False              True              False

   EverTravelledAbroad_No  EverTravelledAbroad_Yes
0                    True                    False
1                    True                    False
2                    True                    False
3                   False                     True
4                    True                    False
     Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
301         822  0.4           0.6       0.285714              0.0

     Employment Type_Government Sector  \
301                              False

     Employment Type_Private Sector/Self Employed  GraduateOrNot_No  \
301                                          True             False

     GraduateOrNot_Yes  FrequentFlyer_No  FrequentFlyer_Yes  \
301               True              True              False

     EverTravelledAbroad_No  EverTravelledAbroad_Yes
301                    True                    False

In [88]:
# csv 파일1 생성 (예시와 다른 형태)
submit = pd.DataFrame({
    'index':test['Unnamed: 0'],
    'y_pred': pred
})

print(submit)
submit.to_csv('0000.csv', index = False)

     index    y_pred
0      920  0.158752
1      777  0.135528
2      696  0.098436
3      907  0.987609
4      675  0.097119
..     ...       ...
492    595  0.076447
493   1091  0.974726
494   1128  0.131915
495   1771  0.985898
496    761  0.990263

[497 rows x 2 columns]

In [89]:
# csv 파일2 생성
vali = pd.read_csv('0000.csv')
print(vali)

     index    y_pred
0      920  0.158752
1      777  0.135528
2      696  0.098436
3      907  0.987609
4      675  0.097119
..     ...       ...
492    595  0.076447
493   1091  0.974726
494   1128  0.131915
495   1771  0.985898
496    761  0.990263

[497 rows x 2 columns]

## 체점
- 수험자는 알 수 없는 부분임

In [90]:
y_test = pd.read_csv("y_test.csv")
roc_auc_score(y_test, pred)

0.788504851004851